---

- src: dev-sec.ssh-hardening
  version: "6.0.0"

- src: unxnn.ansible_users
  version: 'fca2c5a6962db7696329c32a919d3d88cc8623c4'

- src: geerlingguy.docker
  version: "2.5.2"

- src: https://github.com/lukeyeager/ansible-role-hosts.git
  version: '711ba98571f068a8bc6739fa1055ac38fc931010'
  name: lukeyeager.hosts

- src: https://github.com/dholt/ansible-openldap.git
  name: dholt.openldap

- src: andrewrothstein.nss-pam-ldap
  version: "v1.0.2"

- src: andrewrothstein.nss-pam-ldap-configure
  version: "v1.0.6"
