---
worker:
  image:
    repository: rapidsai/rapidsai
    tag: cuda10.0-runtime-ubuntu18.04
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 4
      memory: 8G
      nvidia.com/gpu: 1
    requests:
      cpu: 4
      memory: 8G
      nvidia.com/gpu: 1
